### ISSUE TITLE
Can I use this in a terminal emulator?

### ISSUE THREAD

**Issue by renannprado** [replit/clui#9]
Sorry for the stupid question, but can I use this to write a command line application and render the suggestions in a terminal emulator?

If so, is there any example of it?

**Comment by akramhussein** [comment]
@renannprado have you seen https://repl.it/@clui/demo ?

**Comment by moudy** [comment]
@renannprado the `@replit/clui-input` package can be used anywhere javascript runs so it should work with something like https://github.com/vadimdemedes/ink but I haven't tried.

**Comment by renannprado** [comment]
@akramhussein yes. But I could not understand how that helps me to run exactly that from a terminal emulator instead of a browser.
